### ISSUE TITLE
Topology.spec question

### ISSUE THREAD

**Issue by dancwilliams** [CumulusNetworks/citc-mesos-1#1]
Hello,

This is more of a question than an issue, but I did not know of a better way to ask.

I was looking through how you constructed your playbooks as we are using the nclu module within ansible more and more. Though, my question is around your test directory.

What is the topology.spec file used for? I am sure I am just overlooking something...

Thanks!

Dan W.

**Comment by isharacomix** [comment]
`topology.spec` is simply a metadata file that tells our automated testing applications how to build the topology of Virtual Machines to deploy the playbooks. You'll find one in all of our other `cldemo` repos as well.
